### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by coronapowered** [ISSOtm/gb-asm-tutorial#12]
At line with label Start getting syntax error. Copied and pasted code from site to make sure everything is the same. 
[main - Copy.zip](https://github.com/ISSOtm/gb-asm-tutorial/files/3274341/main.-.Copy.zip)

**Comment by madpew** [comment]
I downloaded the code you provided and added the font-file from the tutorial and it builds just fine.
This is a very old issue so I guess it can be safely closed.

**Comment by ISSOtm** [comment]
Okay then. :shrug:
