### ISSUE TITLE
Displayed Flag Registers and Comparison operations not correct

### ISSUE THREAD

**Issue by propagating** [ISSOtm/gb-asm-tutorial#15]
http://marc.rawer.de/Gameboy/Docs/GBCPUman.pdf
http://www.codeslinger.co.uk/pages/projects/gameboy/hardware.html

The supported flag registers are only:

Z - Zero Flag (a-b = 0)
N - Subtract Flag (used for DAA instructions checking if subtraction was used)
H - Half Carry Flag (carry occurred in first 4 bits)
C - Carry Flag ( A < b)

**Comment by ISSOtm** [comment]
That's correct, but what's the problem?

**Comment by propagating** [comment]
Isn't there an issue in the comparison under Arithmetics & boolean algebra, because we don't have a Carry Reset flag or Zero Reset flag to work with out of the box?


    cp a, 10 ; 42 - 10 = 32,  C reset (42 >= 10), Z reset (42 != 10)
    ; Notice how you can chain comparisons? That comes in handy at times
    cp a, 57 ; 42 - 57 = 241, C set   (42 < 57) , Z reset (42 != 57)
    cp a, 42 ; 42 - 42 = 0,   C reset (42 >= 42), Z set   (42 == 42)

**Comment by ISSOtm** [comment]
Ah, I see; "reset" means the corresponding flag is set to 0, so "Z set" means "Z is set to 1", this does only concern the Z and C flags.

**Comment by propagating** [comment]
Oh, my mistake, sorry about that.
