### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by avivace** [ISSOtm/gb-asm-tutorial#19]
In the readme it's mentioned CC0/public domain, but the license file is MIT.

Fix his and specify the license for content (so a doucmentation license) and for the code snippets.

I don't have strong opinions on this. On pan docs we went for CC0 but here it would be okay to have more constraining ones too (GPL docs?)

**Comment by asiekierka** [comment]
Documentation (text) should *not* be GPL, as discussed by the Free Software Foundation itself even... The FSF offers the GFDL license for documentation; I personally recommend using some variation on Creative Commons 4.0.

The code snippets should absolutely be CC0, in my opinion - given that maximum reuse is encouraged.

**Comment by avivace** [comment]
With "GPL docs" I mean https://www.gnu.org/licenses/fdl-1.3.html

**Comment by ISSOtm** [comment]
Licensing is explained in the tutorial itself:

https://github.com/ISSOtm/gb-asm-tutorial/blob/eaf02135740feefcd6c7d867f51f1a40469def41/src/index.md?plain=1#L31-L41

The tutorial "support" code (i.e. the mdBook preproc and renderer) are MIT; the documentation itself is CC-BY-SA 4.0, and the inline assembly code is CC0.

**Comment by ISSOtm** [comment]
Perhaps this is poorly conveyed by the single `LICENSE` file at the root of the repository, and there should be three of those instead. I'm not sure.

**Comment by avivace** [comment]
> Perhaps this is poorly conveyed by the single `LICENSE` file at the root of the repository, and there should be three of those instead. I'm not sure.

I think it's okay, but the LICENSE paragraph in the README should explain the three points (Website code, Code of the tutorial, Documentation text)
