### ISSUE TITLE
Repository for code

### ISSUE THREAD

**Issue by avivace** [ISSOtm/gb-asm-tutorial#23]
I see that https://github.com/ISSOtm/gb-asm-tutorial-part2 has been created.

I think it would be better to have only one repository, and not one per lesson. It will also ease https://github.com/ISSOtm/gb-asm-tutorial/issues/17 as we will have only one CI/CD pipeline

**Comment by ISSOtm** [comment]
Yes, the goal is to have one repo per project, and thus by part. Each lesson would be one commit, I think.
