### ISSUE TITLE
Elaborate on binary pls

### ISSUE THREAD

**Issue by return2monki** [ISSOtm/gb-asm-tutorial#27]
I thought I understood binary somewhat but in 1.4 binary and hexadecimal you said twice that 10_0000_0000 is 2048 but 0>2>4>8>16>32>64>128>256>512 is what I get.

If I slap the number in a calc or google I get 512 as well.

**Comment by Rangi42** [comment]
Yeah, 2048 would be `%100000000000`, with 12 digits, but:

> So, by applying the same principle, we can say that in base 2, 42 is written as `101010`, and 2048 as `1000000000`.

(actually 512)

> Take %10000000000, aka 2048; when in decimal only 4 digits are required, binary instead needs 10!

 (actually 1024, with 11 digits)

**Comment by ISSOtm** [comment]
Yeah, your understanding is correct. The value should be changed to 1024 and the binary corrected accordingly. Can you open a PR, please?
