### ISSUE TITLE
Stack terminology

### ISSUE THREAD

**Issue by NieDzejkob** [ISSOtm/gb-asm-tutorial#3]
> Notice also that sp is decremented after each push, which essentially means that the stack is placed at the end of RAM, rather than at the beginning (this is called an "ascending" stack).

I'd call this a descending stack. This sounds like a mistake to me. Could you verify?

**Comment by ISSOtm** [comment]
It kinda depends on how you view the memory... if you think of it as address 0000 being the very top, and FFFF being at the very bottom, then the stack is "ascending" as it grows.
On the other hand, since it decreases in addresses, you could say it's a descending (in addresses) stack.
