### ISSUE TITLE
Typo in Hello World!

### ISSUE THREAD

**Issue by oktomus** [ISSOtm/gb-asm-tutorial#7]
Typo at [https://github.com/ISSOtm/gb-asm-tutorial/blob/3176e9da0590a2b92f390fc9db94fd31a58806e4/src/hello-world.html#L186](https://github.com/ISSOtm/gb-asm-tutorial/blob/3176e9da0590a2b92f390fc9db94fd31a58806e4/src/hello-world.html#L186).
It should be *FontTilesEnd*.

**Comment by ISSOtm** [comment]
Yep! This mistake has a fun history :D
